spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.63.147:3306/advertisement?serverTimezone=GMT%2B8
    username: root
    password: Bdbg2181

mybatis:
  mapper-locations: classpath:mapper/*.xml