spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.63.147:3306/advertisement?serverTimezone=GMT%2B8
    username: advertisement
    password: Bdbg2181

mybatis:
  configuration:
    log-impl=org:
      apache:
        ibatis:
          logging:
            stdout:
              StdOutImpl:
    map-underscore-to-camel-case=true:
  mapper-locations: classpath:mapper/*.xml
