spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.124.63.147:3306/advertisement?serverTimezone=GMT%2B8
    username: advertisement
    password: Bdbg2181
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:mapper/*.xml


server:
  port: 8081

logging:
  level:
    org:
      thymeleaf: DEBUG
