spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://112.124.63.147:3306/advertisement?serverTimezone=GMT%2B8
        username: advertisement
        password: Bdbg2181
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        enabled: true
    web:
        resources:
            static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

mybatis:
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        default-statement-timeout: 3000
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: org.example.advertisement_system.entity


server:
    port: 8080
    address: 0.0.0.0
#    servlet:
#        context-path: /advertisement_system

logging:
    level:
        org:
            thymeleaf: warn
            example:
                advertisement_system:
                    service: warn
                    controller: warn
                    dao: warn
            mybatis: warn
        root: info
    file:
        name: /root/log/advertisement_system.log

